milenakos/cat-bot

main.py
=> added regex now

aches.json, main.py
=> New achievement!

main.py
completely untested but what could go wrong
=> make the system not save the files to disk

README.md
=> Emoji download

main.py
=> laugh when people are sad

README.md
=> update db info url

main.py
=> fix battlepass progress not working

main.py
=> indev2 -> indev

main.py
change "Battlepass level" to say "Cattlepass level" instead
=> burger pt 2

aches.json, main.py
I added a few small ideas (and also corrected something), feel free to ignore some of them if you don't want.
I just want to have contributed more than one letter change lol
=> Extra little things

main.py
lol whoops the "r" needs to be capitalized
=> case-sensitivity

main.py
=> add post dog mafia cataine

main.py
yeah i think this one is pretty cut and dry
=> No need to catch cats to reset cataine

main.py
Autocomplete added with discord.app_commands.autocomplete to the functions where cat types are a parameter (/gift, /givecat, /forcespawn) This also means that more than 25 options for this parameter will still work
=> Added autocomplete functionality for /gift, /givecat, and /forcespawn

main.py
now it should be able to fix a cause of being unable to spawn cats
=> make /repair better

main.py
Make the buttons on the tax evasion message actually functional
=> Fix tax evasion

main.py
don't worry, it's just a removed achievement
also this one we both forgot to remove
=> Remove an owner command

main.py
optional options with autocomplete for cat_type for /cat 
ternary operator!!
=> options for /cat

main.py
=> tax collector

main.py
I increased the size of funny by 66%
=> add more funny

main.py
this fixes some inconsistencies and makes funny easier to add
=> make funny its own function

main.py
i had an epiphany that /last could show when the next cat might spawn so that would be pretty neat i think
=> /last estimated next cat time

main.py
well yeah if cataine expired it removed the prism boost message
=> prevent issue with prism message

database.py, main.py
uhhhhh if this is absolute garbage im sorry
=> cant stand (disabled) (prism disabling reference)

main.py
I haven't actually tested this because uh too much effort to get top.gg key so tell me if I did anything stupid
=> tell people how many of a cat type they have when they vote

main.py
maybe in the future this can be replaced with a remove button or something but this works for now
=> allow adding negative cats in /trade to remove cats

database.py, main.py
=> custom cat number

main.py
i've spun the slots like 200 times now and i think this would spice things up a bit
=> randomize reel stop order

main.py
this would fix the problems that i (and only i) cause
=> no negative

main.py
* random reel durations
* blinking arrows showing which row wins
* gambling 🤑 
uhh idk if cat bot has a blank emoji so it's just an empty string right now (also why this pr is a draft)
=> more slots changes

main.py
Add a leaderbaord for Battlepass level for current season
=> Battlepass Level Leaderboard

main.py
<details>
<summary>Click me to learn. </summary>
- Array / List indexes start from 0. Who'd of thought??!?!
- 🫠🔫
</details>
=> I DONT WANT TO TALK ABOUT IT. I AM LE' DUMBASS

main.py
=> I DONT WANT TO TALK ABOUT IT. MK II

main.py
I didn't like how 1 meant you cought either a fine or a nice, not both, so this PR will let you show what is the other cat to catch
=> make fine+nice quest progress more intuitive

main.py
formats your hard drive cutely
=> i love formatting

README.md
maybe more useful api-called information can be added than just "Cat Bot" also idk what color
=> wiki badge

main.py
specifically 31:41.59, 3:14:15.92, 3:14:15.93
=> Add more pies

main.py
removed that horrifying if/elif/elif/elif/else chain on line 2000, a small pr but it works for now
=> refactoring special cought messages

main.py
welp that took a while. here's every change i've made:
line 1880 - now using `divmod` instead of two-liners for cleaner code
1894 - replaced `int(pre_time) == float(pre_time)` with `pre_time % 1 == 0` (pre_time is a float during this check, so it should work just as well)
2020 - using a loop to go through "cutscene" lines instead of hard-coding them in
2202-2287 - replacing multiple `and message.author.id == OWNER_ID` for each command with a single check at the beginning. there's nothing past this point that normal users should access, so we can return early and not have to do 20 more checks
2465 - fixed `False if current_state[num] == "0" else True` :why:
2488, 2496, 2503 - moving `do_funny()` to the top for consistency with earlier private buttons' `do_funny()`
3002, 5650, 5672 - …
=> major refactoring of main.py

main.py
> it's support server
*earth explodes*
=> minor spelling mistake

main.py
=> Add optional param to /prism command to view specific user's owned prisms

main.py
https://discord.com/channels/966586000417619998/1278452426097037362/1372691152813297695
=> Remove CAT_TYPES

main.py
=> fixing recent change

main.py
=> fix logical error

main.py
because why not, you associate battlepass with cattlepass so much nowadays I just had to make this PR
=> Make battlepass command findable by typing "/cattlepass"

main.py
=> cat rain end time bug fix

main.py
when you have more than 10 packs in your inventory, running /packs gives an option to open everything in one click without having to open each pack separately
=> add "open all packs" button

main.py
i mean if you're flipping a coin, you generally have a coin with heads and tails, not a coin with 1 and 2
=> add heads and tails to /roll sides: 2 (coinflip)

main.py
I'd rather the minor unindent on iOS than the random annoying line on Android
=> make battlepass look better on android

main.py
Removed bug that can drop five minutes of cookies.
Add bug that can drop five seconds of cookies.
=> Drop less cookies

main.py
I just wanted a known bug fixed
=> Handle completing multiple cattlepass levels

config/aches.json, main.py
adds a new 'certified yapper' achievement for having 3 or more of these at the end of your catch message:
(i havent actually tested this but in theory it works)
=> certified yapper achievement

main.py
I've seen people worried they lost their streak because it didn't appear when they ran battlepass. This should resolve those concerns.
=> Always show vote streak on running battlepass
